//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MRaabta.BridgeConnector {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConnectorSoap", Namespace="http://tempuri.org/")]
    public partial class Connector : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Get_ConnectionStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetChaseLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAssignedDepotsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_datatableOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_datasetOperationCompleted;
        
        private System.Threading.SendOrPostCallback Insert_dataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Connector() {
            this.Url = global::MRaabta.Properties.Settings.Default.MRaabta_BridgeConnector_Connector;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Get_ConnectionStringCompletedEventHandler Get_ConnectionStringCompleted;
        
        /// <remarks/>
        public event GetChaseLoginCompletedEventHandler GetChaseLoginCompleted;
        
        /// <remarks/>
        public event GetAssignedDepotsCompletedEventHandler GetAssignedDepotsCompleted;
        
        /// <remarks/>
        public event Get_datatableCompletedEventHandler Get_datatableCompleted;
        
        /// <remarks/>
        public event Get_datasetCompletedEventHandler Get_datasetCompleted;
        
        /// <remarks/>
        public event Insert_dataCompletedEventHandler Insert_dataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_ConnectionString", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Get_ConnectionString() {
            object[] results = this.Invoke("Get_ConnectionString", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Get_ConnectionStringAsync() {
            this.Get_ConnectionStringAsync(null);
        }
        
        /// <remarks/>
        public void Get_ConnectionStringAsync(object userState) {
            if ((this.Get_ConnectionStringOperationCompleted == null)) {
                this.Get_ConnectionStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_ConnectionStringOperationCompleted);
            }
            this.InvokeAsync("Get_ConnectionString", new object[0], this.Get_ConnectionStringOperationCompleted, userState);
        }
        
        private void OnGet_ConnectionStringOperationCompleted(object arg) {
            if ((this.Get_ConnectionStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_ConnectionStringCompleted(this, new Get_ConnectionStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetChaseLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetChaseLogin(string depotCode, string Password, string userName) {
            object[] results = this.Invoke("GetChaseLogin", new object[] {
                        depotCode,
                        Password,
                        userName});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetChaseLoginAsync(string depotCode, string Password, string userName) {
            this.GetChaseLoginAsync(depotCode, Password, userName, null);
        }
        
        /// <remarks/>
        public void GetChaseLoginAsync(string depotCode, string Password, string userName, object userState) {
            if ((this.GetChaseLoginOperationCompleted == null)) {
                this.GetChaseLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChaseLoginOperationCompleted);
            }
            this.InvokeAsync("GetChaseLogin", new object[] {
                        depotCode,
                        Password,
                        userName}, this.GetChaseLoginOperationCompleted, userState);
        }
        
        private void OnGetChaseLoginOperationCompleted(object arg) {
            if ((this.GetChaseLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChaseLoginCompleted(this, new GetChaseLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAssignedDepots", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAssignedDepots(string id) {
            object[] results = this.Invoke("GetAssignedDepots", new object[] {
                        id});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAssignedDepotsAsync(string id) {
            this.GetAssignedDepotsAsync(id, null);
        }
        
        /// <remarks/>
        public void GetAssignedDepotsAsync(string id, object userState) {
            if ((this.GetAssignedDepotsOperationCompleted == null)) {
                this.GetAssignedDepotsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAssignedDepotsOperationCompleted);
            }
            this.InvokeAsync("GetAssignedDepots", new object[] {
                        id}, this.GetAssignedDepotsOperationCompleted, userState);
        }
        
        private void OnGetAssignedDepotsOperationCompleted(object arg) {
            if ((this.GetAssignedDepotsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAssignedDepotsCompleted(this, new GetAssignedDepotsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_datatable", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Get_datatable(string query) {
            object[] results = this.Invoke("Get_datatable", new object[] {
                        query});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Get_datatableAsync(string query) {
            this.Get_datatableAsync(query, null);
        }
        
        /// <remarks/>
        public void Get_datatableAsync(string query, object userState) {
            if ((this.Get_datatableOperationCompleted == null)) {
                this.Get_datatableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_datatableOperationCompleted);
            }
            this.InvokeAsync("Get_datatable", new object[] {
                        query}, this.Get_datatableOperationCompleted, userState);
        }
        
        private void OnGet_datatableOperationCompleted(object arg) {
            if ((this.Get_datatableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_datatableCompleted(this, new Get_datatableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_dataset", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Get_dataset(string query) {
            object[] results = this.Invoke("Get_dataset", new object[] {
                        query});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Get_datasetAsync(string query) {
            this.Get_datasetAsync(query, null);
        }
        
        /// <remarks/>
        public void Get_datasetAsync(string query, object userState) {
            if ((this.Get_datasetOperationCompleted == null)) {
                this.Get_datasetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_datasetOperationCompleted);
            }
            this.InvokeAsync("Get_dataset", new object[] {
                        query}, this.Get_datasetOperationCompleted, userState);
        }
        
        private void OnGet_datasetOperationCompleted(object arg) {
            if ((this.Get_datasetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_datasetCompleted(this, new Get_datasetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insert_data", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Insert_data(string query) {
            object[] results = this.Invoke("Insert_data", new object[] {
                        query});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Insert_dataAsync(string query) {
            this.Insert_dataAsync(query, null);
        }
        
        /// <remarks/>
        public void Insert_dataAsync(string query, object userState) {
            if ((this.Insert_dataOperationCompleted == null)) {
                this.Insert_dataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsert_dataOperationCompleted);
            }
            this.InvokeAsync("Insert_data", new object[] {
                        query}, this.Insert_dataOperationCompleted, userState);
        }
        
        private void OnInsert_dataOperationCompleted(object arg) {
            if ((this.Insert_dataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Insert_dataCompleted(this, new Insert_dataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Get_ConnectionStringCompletedEventHandler(object sender, Get_ConnectionStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_ConnectionStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_ConnectionStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetChaseLoginCompletedEventHandler(object sender, GetChaseLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChaseLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChaseLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetAssignedDepotsCompletedEventHandler(object sender, GetAssignedDepotsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAssignedDepotsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAssignedDepotsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Get_datatableCompletedEventHandler(object sender, Get_datatableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_datatableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_datatableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Get_datasetCompletedEventHandler(object sender, Get_datasetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_datasetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_datasetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Insert_dataCompletedEventHandler(object sender, Insert_dataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Insert_dataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Insert_dataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591